name: Static Analysis
on:
    pull_request: {}
    push:
        branches:
            - main
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
    cancel-in-progress: true

permissions: {} # No permissions required

jobs:
    analysis:
        name: Run ${{ matrix.cmd }}
        runs-on: ubuntu-24.04-arm
        strategy:
            fail-fast: false
            matrix:
                cmd:
                    - yarn workspaces run lint:ts
                    - yarn workspaces run lint:style
                    - yarn run lint:js
                    - yarn run lint:workflows
                    - yarn run lint:prettier
                    - yarn run lint:knip
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  cache: "yarn"
                  node-version: "lts/*"

            - name: Install Deps
              run: "yarn install --frozen-lockfile"

            - name: Run check
              run: "${{ matrix.cmd }}"
